# Generated by Django 2.2.5 on 2019-10-16 23:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subbasin',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('recordname', models.CharField(blank=True, db_column='RecordName', max_length=12, null=True)),
                ('gridvalue', models.IntegerField(blank=True, db_column='GridValue', null=True)),
                ('gridarea', models.FloatField(blank=True, db_column='GridArea', null=True)),
                ('gridpercent', models.FloatField(blank=True, db_column='GridPercent', null=True)),
                ('perimeter', models.FloatField(blank=True, db_column='Perimeter', null=True)),
                ('vertexnum', models.IntegerField(blank=True, db_column='VertexNum', null=True)),
                ('basinid', models.IntegerField(blank=True, db_column='BasinID', null=True)),
                ('streamorder', models.IntegerField(blank=True, db_column='StreamOrder', null=True)),
                ('fromxcoord', models.FloatField(blank=True, db_column='FromXCoord', null=True)),
                ('fromycoord', models.FloatField(blank=True, db_column='FromYCoord', null=True)),
                ('toxcoord', models.FloatField(blank=True, db_column='ToXCoord', null=True)),
                ('toycoord', models.FloatField(blank=True, db_column='ToYCoord', null=True)),
                ('cellid', models.IntegerField(blank=True, db_column='CellID', null=True)),
                ('basinname', models.CharField(blank=True, db_column='BasinName', max_length=32, null=True)),
                ('order', models.IntegerField(blank=True, db_column='Order', null=True)),
                ('color', models.IntegerField(blank=True, db_column='Color', null=True)),
                ('numberofcells', models.IntegerField(blank=True, db_column='NumberOfCells', null=True)),
                ('stnmainstemlength', models.FloatField(blank=True, db_column='STNMainstemLength', null=True)),
                ('stncatchmentarea', models.FloatField(blank=True, db_column='STNCatchmentArea', null=True)),
                ('stninterstationarea', models.FloatField(blank=True, db_column='STNInterStationArea', null=True)),
                ('nextstation', models.IntegerField(blank=True, db_column='NextStation', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, db_column='geom', null=True, srid=4326)),
            ],
        ),
    ]
